language: node_js
node_js: 
  - 16

service:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # print the version for logging
  - docker --version 

  # Build
  - docker-compose -f docker-compose.yml build

  # Tagging
  - docker tag udagram-api-user udagram-api-user:v1
  - docker tag udagram-api-feed udagram-api-feed:v1
  - docker tag reverseproxy reverseproxy:v1 
  - docker tag udagram-frontend udagram-frontend:v1

after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Push
  - docker push manhdl/udagram-api-user:v1
  - docker push manhdl/udagram-api-feed:v1
  - docker push manhdl/reverseproxy:v1
  - docker push manhdl/udagram-frontend:v1